### GET /users/l
GET http://localhost:8080/api/users/


### Register admin user
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "email": "admin@admin.com",
  "fullName": "Admin",
  "phoneNumber": "12345678901",
  "password": "12345678",
  "role": "ROLE_ADMIN"
}
### Get token  ЮЗЕР
POST http://localhost:8080/auth/sing-in
Content-Type: application/json

{
  "email": "user@user.com",
  "fullName": "user",
  "phoneNumber": "12345678902",
  "password": "12345678"}


### Get token  АДМИН
POST http://localhost:8080/auth/sing-in
Content-Type: application/json

{
  "email": "admin@admin.com",
  "fullName": "user",
  "phoneNumber": "12345678901",
  "password": "12345678"}

### get user byId
GET http://localhost:8080/api/users/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyQHVzZXIuY29tIiwiZXhwIjoxNzU0MDcyMjA3fQ.OPV07hmkLVqggee3SGScijZOQHmdpReahROlvsHt1FW179t69cFHkFpRvd4jUHwD
Accept: application/json

